{% set name = "openinference-instrumentation-openai-agents" %}
{% set version = "1.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/openinference_instrumentation_openai_agents-{{ version }}.tar.gz
  sha256: 1ecb704ae42f7630f5fd07a2fdfb7141b3abb3200c00664bddca24bec095539f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python  {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<3.14
    - opentelemetry-api
    - opentelemetry-instrumentation
    - opentelemetry-semantic-conventions
    - openinference-instrumentation >=0.1.27
    - openinference-semantic-conventions >=0.1.21
    - typing_extensions
    - wrapt
  run_constrained:
    - openai-agents >=0.2.6

test:
  imports:
    - openinference.instrumentation.openai_agents
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/Arize-ai/openinference/tree/main/python/instrumentation/openinference-instrumentation-openai-agents
  summary: OpenInference OpenAI Agents Instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - visze
